server:
  port: 9003

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha

spring:
  data:
    mongodb:
      uri: ${DATABASE_URL}

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
